name: firebase_auth_app
description: "A Flutter app with Firebase Authentication (Email/Password, Google Sign-In)"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ UI icons
  cupertino_icons: ^1.0.8

  # ✅ Firebase Core (required to initialize Firebase)
  firebase_core: ^3.5.0

  # ✅ Firebase Authentication (email/password, Google, etc.)
  firebase_auth: ^5.3.0

  # ✅ Google Sign-In
  google_sign_in: ^6.2.1

  # ✅ For state management and route guards
  flutter_riverpod: ^3.0.0

  # ✅ For navigation, dialogs, and snackbar support
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
